name: landing_page
description: "QR Menu Landing Page"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_core:
    path: ../../packages/shared_core
  shop_admin:
    path: ../shop_admin
  supabase_flutter: ^2.8.3
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background/
